Develop
vouched/vouched-rest-nodejs pull request #13
Opened 2021-08-11 18:27 UTC by NoelV94

2021-08-11 18:31 UTC, NickLamp submitted a review, later dismissed

2021-08-11 18:57 UTC, natarajaya requested changes
@NoelV94 As discussed – tests will fail when configured to run with the key that belongs to admin user. 
Propose to add another `API_ADMIN_KEY` var and cover both scenarios (requests made with regular user / admin user keys.)

2021-08-13 20:56 UTC, NoelV94 commented
> @NoelV94 As discussed – tests will fail when configured to run with the key that belongs to admin user.
> Propose to add another `API_ADMIN_KEY` var and cover both scenarios (requests made with regular user / admin user keys.)

Modified env variables as discussed
  API_ADMIN_KEY
  API_PRIVATE_KEY
  API_PUBLIC_KEY
  API_URL,
  API_GRAPHQL_URL
  ONBOARD_UR

2021-08-13 20:58 UTC, NickLamp approved these changes

2021-08-13 21:12 UTC, NickLamp approved these changes

2021-08-13 21:12 UTC, natarajaya approved these changes

2021-08-13 21:13 UTC, merged